<script setup>
import { computed, onBeforeUnmount, onMounted, ref, shallowRef, watch } from 'vue'
import { withBase } from 'vitepress'
import { baseline, histogram, processPixels, sampleCredit } from '../../../visualizations/photography/pixels.mjs'
import PhotographyStudyView from './PhotographyStudyView.vue'
const step=ref(0), amount=ref(0), choice=ref(''), answer=ref(''), explanation=ref(''), submitted=ref(false), ready=ref(false), busy=ref(false), error=ref('')
const source=ref(''), rendered=ref(''), originalHist=ref(null), currentHist=ref(null), pixels=shallowRef(null)
let worker, disposed=false, generation=0, timer, processing=false, pending=null
const stages=['整体变亮','只提暗处','直接对照','先预测再验证','换区域试一次']
const control=computed(()=>step.value===1?'shadows':'exposure')
const label=computed(()=>step.value===2 ? (choice.value==='shadows'?'只调暗部 +30':'只调曝光 +1') : step.value===3 ? (submitted.value?(choice.value==='exposure'?'只调曝光 +1':'只调暗部 +30'):'原图 · 等待预测') : step.value===4 ? (choice.value==='exposure'?'只调曝光 +1':choice.value==='shadows'?'只调暗部 +30':'原图 · 先选择') : `${control.value==='shadows'?'暗部':'曝光'} ${amount.value>0?'+':''}${amount.value}`)
const title=computed(()=>['先让整张照片一起变亮','这次只想看清树林','两个办法，放在同一张图上比较','如果只想看清树林，云纹尽量少变呢？','换到右半边：雪山与树林'][step.value])
const instruction=computed(()=>['点「试试 +1」，再看天空云纹和岩壁。曝光会把暗处和亮处一起推亮，白云可能先失去差别。','曝光已经归零。点「试试 +30」，放大深色树林，再切原图。暗处变化更多；天空也可能有少量变化。','交替点击两个按钮。固定盯着同一处云纹，再看树林：哪一版的天空变化更大？','先选择一个办法，再用图片检查。目标是让暗处更可读，同时尽量保留云里的亮暗差。','这是同一张照片的右侧裁切，换了一组观察对象。先选办法，再放大雪山与树林，写出你看见的差别。'][step.value])
function settings(){const s=baseline();if(step.value<2)s[control.value].value=Number(amount.value)||0;else if(step.value===2||step.value===4){if(choice.value==='shadows')s.shadows.value=30;else if(choice.value==='exposure')s.exposure.value=1}else if(submitted.value){if(choice.value==='exposure')s.exposure.value=1;else s.shadows.value=30};return s}
function accept(data){processing=false;if(!disposed&&data.id===generation){if(data.error){error.value=data.error;busy.value=false}else{const c=document.createElement('canvas');c.width=pixels.value.width;c.height=pixels.value.height;c.getContext('2d').putImageData(new ImageData(data.a,c.width,c.height),0,0);rendered.value=c.toDataURL('image/png');currentHist.value=data.histA;busy.value=false}}if(pending){const job=pending;pending=null;send(job)}}
function send(job){processing=true;worker.postMessage(job)}
function render(){if(!pixels.value||disposed)return;busy.value=true;const s=settings(),job={id:++generation,pixels:pixels.value.data,versions:{A:{settings:s},B:{settings:s}}};if(worker){if(processing)pending=job;else send(job)}else{const a=processPixels(job.pixels,s);accept({id:job.id,a,histA:histogram(a)})}}
function go(n){step.value=n;amount.value=0;choice.value=n===2?'exposure':'';answer.value='';explanation.value='';submitted.value=false}
function setAmount(value, input){const n=Number(value);amount.value=Number.isFinite(n)?Math.max(0,Math.min(control.value==='shadows'?60:2,n)):0;if(input)input.value=String(amount.value)}
watch([step,amount,choice,submitted],()=>{clearTimeout(timer);timer=setTimeout(render,70)})
onMounted(async()=>{try{const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=withBase('/photography/fronalpstock.jpg')});if(disposed)return;const c=document.createElement('canvas');c.width=1280;c.height=575;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,1280,575);pixels.value=ctx.getImageData(0,0,1280,575);source.value=c.toDataURL('image/png');originalHist.value=histogram(pixels.value.data);try{worker=new Worker(new URL('../../../visualizations/photography/pixel-worker.mjs',import.meta.url),{type:'module'});worker.onmessage=({data})=>accept(data);worker.onerror=()=>{worker?.terminate();worker=null;processing=false;pending=null;render()}}catch{}ready.value=true;render()}catch{error.value='示例图加载失败，请刷新页面重试。'}})
onBeforeUnmount(()=>{disposed=true;worker?.terminate();clearTimeout(timer)})
</script>
<template>
<section class="tone-lesson" aria-label="曝光与暗部逐步实验">
  <div class="step-line"><span>第 {{step+1}} / 5 步 · {{stages[step]}}</span><button @click="go(0)">从头重来</button></div>
  <nav aria-label="实验步骤"><button v-for="(s,i) in stages" :key="s" :aria-current="step===i?'step':undefined" @click="go(i)">{{i+1}} {{s}}</button></nav>
  <h3>{{title}}</h3><p>{{instruction}}</p><p v-if="error" role="alert">{{error}}</p><p v-if="!ready&&!error" role="status">正在准备山景…</p>
  <template v-if="ready">
    <div class="main-control" v-if="step<2"><label :for="`tone-value-${step}`">{{control==='shadows'?'暗部':'曝光（档）'}}</label><input :id="`tone-value-${step}`" :value="amount" type="number" min="0" :max="control==='shadows'?60:2" :step="control==='shadows'?1:.05" @input="setAmount($event.target.value)" @change="setAmount($event.target.value, $event.target)" @blur="setAmount($event.target.value, $event.target)" /><input :value="amount" type="range" min="0" :max="control==='shadows'?60:2" :step="control==='shadows'?1:.05" :aria-label="control==='shadows'?'调整暗部':'调整曝光'" @input="setAmount($event.target.value)" /><button @click="amount=control==='shadows'?30:1">试试 {{control==='shadows'?'+30':'+1'}}</button><button @click="amount=0">归零</button></div>
    <div v-if="step===2||step===4||(step===3&&submitted)" class="choices" role="group" aria-label="对照两个调整"><button :aria-pressed="choice==='exposure'" @click="choice='exposure'">只调曝光 +1</button><button :aria-pressed="choice==='shadows'" @click="choice='shadows'">只调暗部 +30</button></div>
    <div v-if="step===3&&!submitted" class="choices"><button @click="answer='exposure';choice='exposure';submitted=true">预测：提高曝光</button><button @click="answer='shadows';choice='shadows';submitted=true">预测：提高暗部</button></div>
    <PhotographyStudyView :key="step===4?'transfer':'sample'" :original="source" :current="rendered" :original-hist="originalHist" :current-hist="currentHist" :label="label" :transfer="step===4" :busy="busy" />
    <p class="feedback" role="status" v-if="step===3&&submitted">{{answer==='shadows'?'这个办法更符合本次目标。':'曝光能让树林变亮，但也会明显推亮云和岩壁。'}} 目前显示{{label}}。切换上面的另一种办法，固定观察云纹，再检查树林。暗部调整按像素亮度起作用，不认识“树林”；亮区域也并非完全不变。</p>
    <p class="feedback" v-if="step<3">{{step===0?'看到了什么？云里原本不同的白色是否更接近？不要只看整张照片“更亮了”。':step===1?'树林更亮之后，深浅树丛是否还分得开？如果变成一块灰绿，试着把 +30 降到 +15。':'两个数值不是相同亮度的配方。这里比较的是变化发生在哪里：曝光影响整体；暗部更偏向原来较暗的像素。'}}</p>
    <div v-if="step===4" class="transfer"><label for="photo-explanation">你在哪块区域看到了什么？这次会选哪个办法？</label><textarea id="photo-explanation" v-model="explanation" maxlength="1000" placeholder="例如：切到曝光后，右上雪山……；暗部调整后，右侧树林……，所以我选择……" /><button :disabled="!choice||!explanation.trim()" @click="submitted=true">对照解释要点</button><p v-if="submitted" class="feedback">检查你的解释是否同时提到了两个位置：雪山的亮暗差、树林中的深浅层次。若曝光让雪山更接近白色，而暗部已能看清树林，先选暗部；若整幅都偏暗，可以试较小曝光。这里不按关键词判分，请回图核对自己的判断。</p></div>
    <div class="navigation"><button v-if="step>0" @click="go(step-1)">上一步</button><button v-if="step<4" class="primary" @click="go(step+1)">下一步：{{stages[step+1]}} →</button></div>
    <details><summary>图片出处与实验说明</summary><p><a :href="sampleCredit.url" target="_blank" rel="noopener noreferrer">{{sampleCredit.title}}</a> · {{sampleCredit.author}} · <a :href="sampleCredit.licenseUrl">{{sampleCredit.license}}</a>。第 5 步使用原图右侧裁切，并不是第二张照片。参数只影响本课，不覆盖自由工作台的本地项目。</p></details>
  </template>
</section>
</template>
<style scoped>
.tone-lesson{padding:22px;border:1px solid var(--vp-c-divider);border-radius:16px;background:var(--vp-c-bg-soft);margin:24px 0}.step-line,.navigation{display:flex;justify-content:space-between;align-items:center;gap:10px}.step-line span{font-size:13px;color:var(--vp-c-brand-1);font-weight:700}button{min-height:44px;padding:8px 13px;border:1px solid var(--vp-c-divider);border-radius:8px;background:var(--vp-c-bg);color:var(--vp-c-text-1);cursor:pointer}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid var(--vp-c-brand-1);outline-offset:2px}button:disabled{opacity:.5;cursor:not-allowed}nav{display:flex;gap:5px;margin:15px 0;flex-wrap:wrap}nav button{font-size:12px;padding:5px 10px;flex:1}nav [aria-current],.choices [aria-pressed=true]{border-color:var(--vp-c-brand-1);box-shadow:inset 0 0 0 1px var(--vp-c-brand-1)}h3{font-size:23px;margin:14px 0 8px}p{line-height:1.75;font-size:15px;margin:10px 0}.main-control{display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:12px 0}.main-control input[type=number]{width:80px;padding:8px;background:var(--vp-c-bg);border:1px solid var(--vp-c-divider);border-radius:7px;min-height:44px}.main-control input[type=range]{flex:1;min-width:100px;min-height:44px;accent-color:var(--vp-c-brand-1)}.choices{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}.feedback{padding:12px 15px;border-left:3px solid var(--vp-c-brand-1);background:var(--vp-c-bg)}.transfer label{display:block;margin:14px 0 8px;font-weight:600}.transfer textarea{width:100%;min-height:88px;padding:12px;background:var(--vp-c-bg);border:1px solid var(--vp-c-divider);border-radius:8px;resize:vertical}.navigation{margin-top:20px}.primary{background:var(--vp-c-brand-1);color:white;margin-left:auto}details{font-size:12px;margin-top:18px}summary{cursor:pointer}details p{font-size:12px}@media(max-width:560px){.tone-lesson{padding:13px}h3{font-size:20px}.main-control input[type=range]{order:2;flex-basis:100%}nav button{flex-basis:28%}.step-line{align-items:flex-start}}
</style>
